"""Build an INT8 PTQ (implicit quantisation) engine for the laya s512 bucket.

Unlike the INT4 WoQ attempt (weight-only, explicit), this is implicit PTQ: the builder chooses
per-layer int8 kernels and derives activation scales from a calibration set that is run through
the network. All five ONNX inputs are fed per sample (4x int64 + 1x bool), because the network
cannot take a forward step without them and calibrating on partially-defined inputs would
measure activation ranges the model never produces.

Calibration data: calib_s512_q/calib -- 128 samples at the s512 bucket, generated by laya's own
build_sequence (see scripts/20_build_calib.py), so the token mix is the one the model serves.
"""
import argparse
import glob
import json
import os
import time

import numpy as np
import cuda.cudart as cudart
import tensorrt as trt

NP_OF = {trt.DataType.FLOAT: np.float32, trt.DataType.HALF: np.float16,
         trt.DataType.INT32: np.int32, trt.DataType.INT64: np.int64,
         trt.DataType.BOOL: np.bool_, trt.DataType.INT8: np.int8,
         trt.DataType.UINT8: np.uint8}


class EntropyCalib(trt.IInt8EntropyCalibrator2):
    """Entropy calibrator over a directory-per-sample dataset."""

    def __init__(self, dirs, spec, cache_in, cache_out):
        trt.IInt8EntropyCalibrator2.__init__(self)
        self.dirs = dirs
        self.spec = spec            # name -> (numpy dtype, nbytes)
        self.cache_in = cache_in
        self.cache_out = cache_out
        self.ptr = {}
        self.idx = 0
        self.requested = set()
        self.ptr_mismatch = []

    def get_batch_size(self):
        return 1

    def _devptr(self, name):
        p = self.ptr.get(name)
        if p is None:
            _, nbytes = self.spec[name]
            err, p = cudart.cudaMalloc(nbytes)
            if err != 0:
                raise RuntimeError("cudaMalloc(%d) for %s failed err=%d" % (nbytes, name, err))
            self.ptr[name] = p
        return p

    def get_batch(self, names):
        if self.idx >= len(self.dirs):
            return None
        for n in names:
            self.requested.add(n)
        d = self.dirs[self.idx]
        self.idx += 1
        out = []
        for n in names:
            if n not in self.spec:
                raise RuntimeError("calibrator asked for unknown input %r" % n)
            dtype, nbytes = self.spec[n]
            p = os.path.join(d, n + ".npy")
            if not os.path.exists(p):
                raise RuntimeError("missing %s" % p)
            a = np.ascontiguousarray(np.load(p).astype(dtype).reshape(-1))
            if a.nbytes != nbytes:
                self.ptr_mismatch.append("%s: %d != %d" % (n, a.nbytes, nbytes))
                raise RuntimeError("sample %s: %s has %d bytes, network wants %d"
                                   % (d, n, a.nbytes, nbytes))
            ret = cudart.cudaMemcpy(self._devptr(n), a.ctypes.data, nbytes,
                                    cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)
            err = ret[0] if isinstance(ret, tuple) else ret
            if err != 0:
                raise RuntimeError("cudaMemcpy H2D for %s failed err=%d" % (n, err))
            out.append(int(self._devptr(n)))
        if self.idx % 32 == 0 or self.idx == len(self.dirs):
            print("### calib fed %d/%d" % (self.idx, len(self.dirs)), flush=True)
        return out

    def read_calibration_cache(self):
        if self.cache_in and os.path.exists(self.cache_in):
            with open(self.cache_in, "rb") as f:
                b = f.read()
            print("### read existing calibration cache %s (%d bytes)" % (self.cache_in, len(b)),
                  flush=True)
            return b
        return None

    def write_calibration_cache(self, cache):
        if self.cache_out:
            with open(self.cache_out, "wb") as f:
                f.write(cache)
            print("### wrote calibration cache %s (%d bytes)" % (self.cache_out, len(cache)),
                  flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--onnx", required=True)
    ap.add_argument("--calib", required=True)
    ap.add_argument("--engine", required=True)
    ap.add_argument("--caltable", required=True)
    ap.add_argument("--cache-in", default=None)
    ap.add_argument("--timing-in", default=None)
    ap.add_argument("--timing-out", default=None)
    ap.add_argument("--layerinfo", default=None)
    ap.add_argument("--workspace-mb", type=int, default=2048)
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--no-detail", action="store_true",
                    help="build without DETAILED profiling verbosity")
    args = ap.parse_args()

    lvl = trt.Logger.VERBOSE if args.verbose else trt.Logger.INFO
    logger = trt.Logger(lvl)
    trt.init_libnvinfer_plugins(logger, "")

    t0 = time.time()
    builder = trt.Builder(logger)
    network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
    parser = trt.OnnxParser(network, logger)
    with open(args.onnx, "rb") as f:
        blob = f.read()
    print("### onnx %s bytes=%d" % (args.onnx, len(blob)), flush=True)
    if not parser.parse(blob):
        for i in range(parser.num_errors):
            print("### ONNX PARSE ERROR: %s" % parser.get_error(i), flush=True)
        raise SystemExit("ONNX parse failed")
    print("### parsed in %.1fs" % (time.time() - t0), flush=True)

    spec, shapes = {}, {}
    for i in range(network.num_inputs):
        t = network.get_input(i)
        np_dt = NP_OF[t.dtype]
        shp = tuple(int(d) for d in t.shape)
        nbytes = int(np.prod(shp)) * np.dtype(np_dt).itemsize
        spec[t.name] = (np_dt, nbytes)
        shapes[t.name] = {"dtype": str(t.dtype), "shape": list(shp), "nbytes": nbytes}
        print("### net input %-15s %-6s %-10s nbytes=%d" % (t.name, t.dtype, shp, nbytes),
              flush=True)
    for i in range(network.num_outputs):
        t = network.get_output(i)
        print("### net output %-15s %-6s %s" % (t.name, t.dtype, tuple(int(d) for d in t.shape)),
              flush=True)

    cfg = builder.create_builder_config()
    cfg.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, args.workspace_mb << 20)
    cfg.set_flag(trt.BuilderFlag.FP16)
    cfg.set_flag(trt.BuilderFlag.INT8)
    if not args.no_detail:
        cfg.profiling_verbosity = trt.ProfilingVerbosity.DETAILED
    _st = getattr(trt.BuilderFlag, "STRONGLY_TYPED", None)
    print("### flags: INT8=%s FP16=%s stronglyTyped=%s detail=%s"
          % (cfg.get_flag(trt.BuilderFlag.INT8), cfg.get_flag(trt.BuilderFlag.FP16),
             "n/a (absent in TRT %s)" % trt.__version__ if _st is None
             else cfg.get_flag(_st), not args.no_detail), flush=True)

    tc_used = None
    if args.timing_in and os.path.exists(args.timing_in):
        with open(args.timing_in, "rb") as f:
            cfg.set_timing_cache(cfg.create_timing_cache(f.read()), False)
        tc_used = args.timing_in
        print("### loaded timing cache %s" % args.timing_in, flush=True)
    else:
        cfg.set_timing_cache(cfg.create_timing_cache(b""), False)
        print("### no timing cache loaded (fresh)", flush=True)

    dirs = sorted(glob.glob(os.path.join(args.calib, "sample_*")))
    if not dirs:
        raise SystemExit("no calibration samples under %s" % args.calib)
    print("### calibration samples: %d" % len(dirs), flush=True)
    cal = EntropyCalib(dirs, spec, args.cache_in, args.caltable)
    cfg.int8_calibrator = cal

    print("### building ...", flush=True)
    t0 = time.time()
    ser = builder.build_serialized_network(network, cfg)
    build_s = time.time() - t0
    if ser is None:
        raise SystemExit("build_serialized_network returned None")
    print("### built in %.1fs serialized=%d bytes (%.2f MiB)"
          % (build_s, ser.nbytes, ser.nbytes / 1048576.0), flush=True)
    print("### calibrator requested inputs: %s" % sorted(cal.requested), flush=True)
    print("### calibrator never asked for: %s" % sorted(set(spec) - cal.requested), flush=True)

    with open(args.engine, "wb") as f:
        f.write(ser)
    print("### wrote engine %s" % args.engine, flush=True)

    if args.timing_out:
        try:
            with open(args.timing_out, "wb") as f:
                f.write(cfg.get_timing_cache().serialize())
            print("### wrote timing cache %s" % args.timing_out, flush=True)
        except Exception as e:
            print("### timing cache write failed: %s" % e, flush=True)

    # Per-layer precision evidence, from the engine that was actually written.
    try:
        eng = trt.Runtime(logger).deserialize_cuda_engine(ser)
        insp = eng.create_engine_inspector()
        txt = insp.get_engine_information(trt.LayerInformationFormat.JSON)
        with open(args.layerinfo or (args.engine + ".layers.json"), "w") as f:
            f.write(txt)
        d = json.loads(txt)
        layers = d.get("Layers", [])
        print("### inspector layers=%d; sample=%s" % (len(layers), json.dumps(layers[0])[:400]),
              flush=True)
        from collections import Counter
        prec = Counter(str(L.get("Precision")) for L in layers if isinstance(L, dict))
        typ = Counter(str(L.get("LayerType")) for L in layers if isinstance(L, dict))
        print("### precision histogram: %s" % dict(prec), flush=True)
        print("### layer type histogram: %s" % dict(typ), flush=True)
    except Exception as e:
        print("### layer info dump failed: %s: %s" % (type(e).__name__, e), flush=True)

    print("### peak host/device mem stats, build_s=%.1f timing_cache=%s" % (build_s, tc_used),
          flush=True)
    print("### DONE", flush=True)


if __name__ == "__main__":
    main()
